apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: python-script
  title: Python Script Test
  description: Test out custom python execution action 
spec:
  owner: development
  type: service

  parameters:
    - title: Python Script Options
      required:
        - python_path
      properties:
        python_path:
          title: Python Path
          type: string
          description: Python path to be used
          enum:
            - python 
            - python3
        script_args:
          title: Script Arguments
          type: array
          description: Script arguments required 
          items:
            type: string
            title: Script Arguments
            description: Enter a script argument
          ui:options:
            addable: true
            orderable: false
            removable: true

  steps:
    - id: fetch-script
      name: Fetch Python Script
      action: fetch:plain:file
      input:
        url: ./hello.py
        targetPath: hello.py
    
    - id: execute-python
      name: Execute python script
      action: custom:execute-python
      input:
        script: hello.py
        pythonPath: ${{ parameters.python_path }}
        args: ${{ parameters.script_args }}
