apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{values.app_name}}
  description: java springboot app for users - named ${{values.app_name}}
  annotations:
    github.com/project-slug: ben14132-01/${{values.app_name}}
    backstage.io/techdocs-ref: dir:.
    'jenkins.io/job-full-name': java/${{values.app_name}}
    argocd/app-name: ${{ values.app_name }}
    grafana/dashboard-selector: "tags @> 'backstage' && tags @> 'monitoring'"
spec:
  type: service
  owner: development
  lifecycle: experimental 
  providesApis:
    - ${{values.app_name}}-actuator-api
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: ${{values.app_name}}-actuator-api
  title: ${{values.app_name}} Actuator API
  description: Spring Boot Actuator endpoints for monitoring and management
spec:
  type: openapi
  lifecycle: experimental
  owner: development
  definition: |
    openapi: 3.0.0
    info:
      title: ${{values.app_name}} Actuator API
      description: Spring Boot Actuator management endpoints
      version: 1.0.0
    servers:
      - url: http://localhost:8082
        description: Local development server
    paths:
      /actuator:
        get:
          summary: Actuator discovery endpoint
          description: Lists all available actuator endpoints
          responses:
            '200':
              description: Available actuator endpoints
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      _links:
                        type: object
                        description: HAL-style links to available endpoints
      /actuator/health:
        get:
          summary: Application health status
          description: Shows application health information
          responses:
            '200':
              description: Application is healthy
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      status:
                        type: string
                        enum: [UP, DOWN, OUT_OF_SERVICE, UNKNOWN]
            '503':
              description: Application is unhealthy
      /actuator/info:
        get:
          summary: Application information
          description: General information about the application
          responses:
            '200':
              description: Application information
              content:
                application/json:
                  schema:
                    type: object
      /actuator/metrics:
        get:
          summary: Application metrics
          description: Lists available application metrics
          responses:
            '200':
              description: Available metrics
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      names:
                        type: array
                        items:
                          type: string
      /actuator/metrics/{metricName}:
        get:
          summary: Specific metric details
          description: Get details for a specific metric
          parameters:
            - name: metricName
              in: path
              required: true
              schema:
                type: string
          responses:
            '200':
              description: Metric details
              content:
                application/json:
                  schema:
                    type: object
      /actuator/env:
        get:
          summary: Environment properties
          description: Shows environment and configuration properties
          responses:
            '200':
              description: Environment information
              content:
                application/json:
                  schema:
                    type: object
    components:
      schemas:
        HealthStatus:
          type: object
          properties:
            status:
              type: string
              enum: [UP, DOWN, OUT_OF_SERVICE, UNKNOWN]
            components:
              type: object
              description: Health of individual components